apiVersion: v1
kind: PersistentVolume
metadata:
  name: ub-efs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ub-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b13440ec0fe2f443
