apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"karpenter","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"karpenter","app.kubernetes.io/version":"0.34.0","helm.sh/chart":"karpenter-v0.34.0"},"name":"karpenter","namespace":"kube-system"},"spec":{"ports":[{"name":"http-metrics","port":8000,"protocol":"TCP","targetPort":"http-metrics"}],"selector":{"app.kubernetes.io/instance":"karpenter","app.kubernetes.io/name":"karpenter"},"type":"ClusterIP"}}
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-02-22T01:12:50Z"
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.34.0
    helm.sh/chart: karpenter-v0.34.0
  name: karpenter
  namespace: kube-system
  resourceVersion: "2029468"
  uid: 78331220-45f2-455c-a7c8-6c7e3670e873
spec:
  clusterIP: 10.100.220.170
  clusterIPs:
  - 10.100.220.170
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/name: karpenter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
